apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dokuwiki
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  timeout: 1m0s
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/dev
  prune: true
