apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-dev
  namespace: flux-ns
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-ns
  path: ./infrastructure/dev
  prune: true
