apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-nginx-rb
  namespace: nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-cr
subjects:
- kind: ServiceAccount
  name: flux-sa
  namespace: flux-system
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
