apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-nginx-rb
  namespace: nginx-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-cr
subjects:
  - kind: ServiceAccount
    name: flux-sa
    namespace: nginx
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
