apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  releaseName: nginx-ingress-controller
  chart:
    spec:
      chart: nginx-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 0h5m0s
  install:
    remediation:
      retries: 3
  values:
    nameOverride: "nginx"
    fullnameOverride: "nginx"
    podSecurityPolicy:
      enabled: false