apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dokuwiki
spec:
  releaseName: dokuwiki
  chart:
    spec:
      chart: dokuwiki
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 0h5m0s
  install:
    remediation:
      retries: 3
  values:
    podSecurityPolicy:
      enabled: false
    metrics:
      enabled: false
    ingress:
      enabled: true
      ingressClassName: "nginx"
      path: /
      hostname: dokuwiki.local
