apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-sa-rb
  namespace: flux-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux-role
subjects:
  - name: flux-sa
    namespace: flux-ns
    kind: ServiceAccount
